"""initial schema

Revision ID: 329164022a6f
Revises: 
Create Date: 2026-07-18 20:10:44.371681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329164022a6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('height', sa.String(length=32), nullable=True),
    sa.Column('mass', sa.String(length=32), nullable=True),
    sa.Column('hair_color', sa.String(length=64), nullable=True),
    sa.Column('skin_color', sa.String(length=64), nullable=True),
    sa.Column('eye_color', sa.String(length=64), nullable=True),
    sa.Column('birth_year', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swapi_id')
    )
    op.create_index('ix_characters_name', 'characters', ['name'], unique=False)
    op.create_index('ix_characters_swapi_id', 'characters', ['swapi_id'], unique=True)
    op.create_table('films',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('producer', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('opening_crawl', sa.String(), nullable=True),
    sa.Column('votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swapi_id')
    )
    op.create_index('ix_films_swapi_id', 'films', ['swapi_id'], unique=True)
    op.create_index('ix_films_title', 'films', ['title'], unique=False)
    op.create_table('starships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=64), nullable=True),
    sa.Column('length', sa.String(length=64), nullable=True),
    sa.Column('crew', sa.String(length=64), nullable=True),
    sa.Column('passengers', sa.String(length=64), nullable=True),
    sa.Column('starship_class', sa.String(length=128), nullable=True),
    sa.Column('votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swapi_id')
    )
    op.create_index('ix_starships_name', 'starships', ['name'], unique=False)
    op.create_index('ix_starships_swapi_id', 'starships', ['swapi_id'], unique=True)
    op.create_table('character_films',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'film_id'),
    sa.UniqueConstraint('character_id', 'film_id', name='uq_character_film')
    )
    op.create_table('starship_films',
    sa.Column('starship_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('starship_id', 'film_id'),
    sa.UniqueConstraint('starship_id', 'film_id', name='uq_starship_film')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starship_films')
    op.drop_table('character_films')
    op.drop_index('ix_starships_swapi_id', table_name='starships')
    op.drop_index('ix_starships_name', table_name='starships')
    op.drop_table('starships')
    op.drop_index('ix_films_title', table_name='films')
    op.drop_index('ix_films_swapi_id', table_name='films')
    op.drop_table('films')
    op.drop_index('ix_characters_swapi_id', table_name='characters')
    op.drop_index('ix_characters_name', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
